### ISSUE TITLE
Any way to get the id of the worker

### ISSUE THREAD

**Issue by mg03** [stefantalpalaru/pool#1]
Hi
Firstly, this is a nice utility. Thanx
Qs: Im creating 5 workers using pool.New. How do I pass in the id lets say ids are 1 to 5. Or how do I get the worker  ids in the Job result?

**Comment by stefantalpalaru** [comment]
I added job and worker IDs in the Job struct: https://github.com/stefantalpalaru/pool/blob/0942863e95f8f50c573af7680ff2b2df63f0482f/examples/pool_example.go#L47

**Comment by mg03** [comment]
cool thanx .. this helps a lot ....
