### ISSUE TITLE
Case for non-determistic number of jobs

### ISSUE THREAD

**Issue by python152** [stefantalpalaru/pool#4]
hi - 
It doesn't look this project is not in active development, but I will ask anyway.
I have a use case where the number of jobs is non-deterministic: in the sense that each Job may or may not generate new Jobs. The termination condition is no new jobs are generated by all submitted jobs. Can this pool structure support such use case? TIA.

**Comment by python152** [comment]
never mind, I think your web crawler is good example for it. thx

**Comment by stefantalpalaru** [comment]
> this project is not in active development

It is, but the API is stable and no new bugs surfaced in the last couple of years.
